name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main  # Хук сработает только при пуше в главную ветку

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: z923163a.beget.tech         # Сервер Beget для FTP соединения
          username: z923163a_k      # Измените на ваш FTP-логин от Beget
          password: ${{ secrets.FTP_PASSWORD }} # Подставится автоматически из Secrets
          server-dir: /kidlearn.ru/      # Папка на Beget, куда заливать сайт (обычно public_html/)
          security: ftps
